#macro SET_LOCKED		0
#macro SET_ANGLE		1
#macro SET_DISTANCE		2
#macro TEXTURE_PNG		0
#macro TEXTURE_BUFFER	1
#macro TEXTURE_MODE		TEXTURE_PNG
#macro BUFFER_NORMAL	0
#macro BUFFER_COMPRESS	1 // WARNING 1.2.3 AND LOWER, BUFFER COMPRESS MEMORY LEAK
#macro BUFFER_MODE		BUFFER_NORMAL